### ISSUE TITLE
freebsd反向代理失效

### ISSUE THREAD

**Issue by ykla** [bjtulug/bjtu-mirror-issues#13]
是否被ban ip了…
pkg失效数天…

**Comment by chestnutprog** [comment]
由于一些不可描述的原因，学校信息中心从8月17日关闭了v4入站，预计影响到8月底。
我刚刚试着开了cloudflare，等几个小时DNS生效后应该能恢复服务，但是速度可能会有较大影响。
我校镜像站流量不是很大，学校一直不怎么重视，还请理解一下。

**Comment by supersndqd** [comment]
能提供一下ipv6的地址吗

**Comment by chestnutprog** [comment]
v4外部访问应该恢复正常了

**Comment by chestnutprog** [comment]
由于清查校外域名，bjtulug.org近几天将无法正常使用，预计将在墙外301跳回解决。

**Comment by ykla** [comment]
正常使用
