### ISSUE TITLE
优麒麟系统镜像站申请

### ISSUE THREAD

**Issue by liumin0322** [bjtulug/bjtu-mirror-issues#15]
Hi~我是优麒麟社区的Mina，感谢贵站对国内外开源软件镜像的维护，为用户提供镜像下载。优麒麟的镜像也希望申请加入贵站，我们会有工作人员配合贵站同步或上传各版本的镜像。
优麒麟官网：http://www.ubuntukylin.com

镜像同步方式：					
参考用例：RSYNC_PASSWORD="user"  /usr/bin/rsync -azHv --delete --port=8873  --progress  user@service.ubuntukylin.com::rsync   ~/data				
rsync同步地址: user@service.ubuntukylin.com::rsync /data

**Comment by ykla** [comment]
建议加群t.me/bjtumirror

**Comment by chestnutprog** [comment]
已同步 https://mirror.bjtu.edu.cn/ubuntukylin/
