### ISSUE TITLE
申请加源NeuroDebian

### ISSUE THREAD

**Issue by hyiltiz** [bjtulug/bjtu-mirror-issues#16]
能否考虑一下 NeuroDebian[0] 的镜像站点。此源囊括认知科学、神经科学、实验/认知心理学、生物工程 等领域经常用到的科研软件和工具（fMRI等脑图分析，Psychtoolbox等心理学实验工具包），维护时间长且稳定。

很多科研单位（如心理学院系、神经科学院系、生物科学院系等）都依赖此源。NeuroDebian 里基本上都是科研类应用程序，所占硬盘空间相对较小（小于100GB）。维护也仅需cron一下rsync即可。推荐更新周期是24小时——大部分时候只会更新timestamp，并不会导致过大的流量。

[0] http://neuro.debian.net/

**Comment by chestnutprog** [comment]
已同步: https://mirror.bjtu.edu.cn/neurodebian/
