### ISSUE TITLE
freebsd pkg源 连接不上了

### ISSUE THREAD

**Issue by stzz1** [bjtulug/bjtu-mirror-issues#22]
Updating bjtu repository catalogue...
pkg: http://mirror.bjtu.edu.cn/reverse/freebsd-pkg/FreeBSD:13:amd64/quarterly/meta.txz: Service Unavailable
repository bjtu has no meta file, using default settings
pkg: http://mirror.bjtu.edu.cn/reverse/freebsd-pkg/FreeBSD:13:amd64/quarterly/packagesite.pkg: Service Unavailable
pkg: http://mirror.bjtu.edu.cn/reverse/freebsd-pkg/FreeBSD:13:amd64/quarterly/packagesite.txz: Service Unavailable
Unable to update repository bjtu
Error updating repositories!

**Comment by chestnutprog** [comment]
请耐心等待特殊时期过去（

**Comment by chestnutprog** [comment]
应该恢复了
